### PR TITLE
Merge handler and iter8ctl into etc3 (#242)

### PR DESCRIPTION
**Pull request by kalantar**
This addresses issue iter8-tools/iter8#951; it replaces PR https://github.com/iter8-tools/etc3/pull/240 so that go install of iter8ctl could be tested.
Includes:

* merge handler project

Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>

* fold iter8ctl repo into etc3

Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>

* fix build

Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>

* more iter8ctl testing, docker build

Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>

* set controlplane startup timeout

Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>

* test with go 1.17

Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>

* test with go 1.17

Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>

* test with go 1.17

Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>

* remove ubuntu

Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>

* rename workflow; add targets for each buld

Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>

### CODE REVIEW

**Comment by kalantar** [comment]
Tested that can install iter8ctl using ((tested using ref = `mergerepos`):

```bash
go install github.com/iter8-tools/etc3/iter8ctl@<ref>
```

Also verified that iter8ctl could be used as part of "Your first experiment":

```bash
$ iter8ctl assert -c completed -c winnerFound
All conditions satisfied.
$ iter8ctl describe

****** Overview ******
Experiment name: hello-experiment-57a46
Experiment namespace: default
Target: hello
Testing pattern: Conformance
Deployment pattern: Progressive
...
```

Since were able to verify install/use of iter8ctl, created this PR to merge into main.

**Review by sriumcp — CHANGES_REQUESTED** [review]
Could we please create two build-and-push workflows, one for `etc3` and one for `handler` in `.github/workflows` folder?

The effect we want to achieve is straight forward.
1. Build and push whenever there are changes to etc3 or handler (even in a `non-main` branch). Currently only `main` branches are built and pushed.
2. Build and push when there are releases (this is  already handled).
3. Build and test if there are PRs (this is already handled).

We should be able to test the handler parts of the change without having to merge in main, and that is relatively easy to accomplish.

In anycase, we do need the workflow that builds and pushes the handler, which is apparently missing.

**Comment by kalantar** [comment]
> In anycase, we do need the workflow that builds and pushes the handler, which is apparently missing.

It is here: https://github.com/iter8-tools/etc3/blob/mergerepos/.github/workflows/build-and-push-etc3.yaml#L128-L134

**Comment by sriumcp** [comment]
> > In anycase, we do need the workflow that builds and pushes the handler, which is apparently missing.
> 
> It is here: https://github.com/iter8-tools/etc3/blob/mergerepos/.github/workflows/build-and-push-etc3.yaml#L128-L134
> 
> We may still need for non-main branches

1. https://github.com/iter8-tools/etc3/blob/0ed05d2b35a173e1cc7f6a8e160f8d4ebf003754/.github/workflows/build-and-push-etc3.yaml#L128-L134 is not going to work. The name of the target image for task runner appears to be the same as that for etc3. We basically need to replace ${{ env.REPO }} with actual names. `etc3` for controller, and `taskrunner` for handler.
2. We do want to merge into `mergerepos` branch first and test it by creating an Iter8 repo PR to make sure this works. That is the cleanest way to be sure there are no bugs here. I will do a code review as part of the PR process, but this PR involves 114 files, and we want to be sure we got it right. Iter8 repo already has the workflows to do the e2e tests which we can leverage once we have the ability to build images off of branches in etc3.

**Comment by kalantar** [comment]
I need some help to clarify what the approach for build workflows should be. I see a desire for multiple workflows. If we define separate workflows for controller, taskrunner, and iter8ctl, then presumably, each should be run only for relevant changes.

taskrunner (and iter8ctl) depends on the controller so should be run whenever its dependencies change.  For example, for taskrunner this would be:

```yaml
paths:
  - ‘taskrunner/**’
  - ‘api/**’
  - ‘controllers/util.go’
```

Is this what we want? Or to just run every test for any change? 

At present there *is* a separate workflow for iter8ctl, but this is meant to augment the existing workflow by running the tests for additional platforms (ie. macos).  By itself, it is not sufficient.

**Comment by sriumcp** [comment]
Here's how I would structure the workflows...
***
Lets start by listing the atomic jobs we need, and then discuss when those jobs need to be run.
***
1. Build and test etc3
2. Build and test task runner
3. Build and test iter8ctl
4. Build and push etc3
5. Build and push task runner
***
1, 2, 3, 4 and 5 are run whenever a PR is merged to any branch (including main) or a new release is created for the repo (testing during releases is redundant, but its ok to have them; our tests are not 100% consistent, running more often shows up the intermittent failures).
***
1, 2, 3 needs to happen whenever a PR wants to make changes to any branch of the repo
***
4 requires 1, 2, and 3 to pass
5 requires 1, 2, and 3  to pass
***

This is the simplest and most straightforward way to structure the workflows. Yes, there is some redundant testing going on, but we don't need to prematurely optimize the workflows at this point. If we feel a pressing need to optimize testing (later), we can do so by introducing more stringent if conditions / path based conditions (later).

***

**Comment by kalantar** [comment]
ok. great. I was concerned about creating a bunch of specific statements. TBH, I would even prefer the simplification of testing things all together. `go test ./...` tests everything and does not require extra effort. At least initially, we did not put the controller in its own sub-directory (we did this so that merging into v0.8 branch will be easier). This means that to test the controller will require listing the directories it uses. Best to avoid, I think.
In the future, we can rearrange and specialize if necessary. 
The only exception here is iter8ctl which needs to be tested on multiple platforms. To do this, I've added a job for the additional platforms.

**Comment by kalantar** [comment]
This now includes the requested changes that were requested above; they were added via a pull request on the branch.

**Review by sriumcp — APPROVED** [review]
lgtm.

**Pull request merged**
